models:
  model_001:
    input_dim: 400
    layers_config:
      LogicLayer001:
        connections: random
        device: cuda
        grad_factor: 2
        implementation: cuda
        in_dim: 400
        out_dim: 2500
      LogicLayer002:
        connections: random
        device: cuda
        grad_factor: 2
        implementation: cuda
        in_dim: 2500
        out_dim: 2500
    learning_rate: 0.01
    output_size: 10
    tau: 10
